### PR TITLE
Build openjdk 17 chiselled image

### PR DESCRIPTION
**Pull request by vpa1977**
#### Changes proposed in this pull request:
 -  build openjdk 17 chiselled image by:
      - generating runtime image using jlink 
      - deploying runtime image into chiselled container with openjdk dependencies
- package openjdk 17 legal statements (note, those can be probably split out into separate MR from coding point of view, but for legal reason, probably best kept in the same MR). 
- update pdfbox version (otherwise it does not build)
- update images to reference openjdk 17

- [*] I have signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

*Picture of a cool ROCK:*

### CODE REVIEW

**Review by cjdcordeiro — COMMENTED** [review]
is all of these LEGAL needed? @valentincanonical should also review this

**Comment by vpa1977** [comment]
I have seen corretto image(?) package legalise inside .tar.gz which we might also do in order to save uncompressed space

**Comment by valentincanonical** [comment]
> I have seen corretto image(?) package legalise inside .tar.gz which we might also do in order to save uncompressed space

yes, we might want to reproduce this approach to avoid the many file changes and unnecessary expanding of unused (at runtime) files.

**Comment by vpa1977** [comment]
> > I have seen corretto image(?) package legalise inside .tar.gz which we might also do in order to save uncompressed space
> 
> yes, we might want to reproduce this approach to avoid the many file changes and unnecessary expanding of unused (at runtime) files.

Removed openjdk license from Dockerfile directory, compressed legalise inside docker

**Review by cjdcordeiro — COMMENTED** [review]
Right, so I've rebased the destination branch so that it has the latest renaming changes from jre8. This obviously created conflicts so I've resolved them in your branch already.

I think this is ready for a final pass. The only open question is the need for the chisel-releases fork. Do we actually need it? I see you have some custom slices in that fork, but some are not used (like busybox). So:
1. could you maybe propose those slices upstream? :) the more contributors we have the merrier...and you've already done the work so why not become a contributor
2. do we actually need that fork? At first glance, only `libgraphite2-3` seems to be missing from upstream, so can't we just quickly add it upstream? Or remove it if it is not needed...

**Comment by vpa1977** [comment]
> Right, so I've rebased the destination branch so that it has the latest renaming changes from jre8. This obviously created conflicts so I've resolved them in your branch already.
> 
> I think this is ready for a final pass. The only open question is the need for the chisel-releases fork. Do we actually need it? I see you have some custom slices in that fork, but some are not used (like busybox). So:
> 
> 1. could you maybe propose those slices upstream? :) the more contributors we have the merrier...and you've already done the work so why not become a contributor
> 2. do we actually need that fork? At first glance, only `libgraphite2-3` seems to be missing from upstream, so can't we just quickly add it upstream? Or remove it if it is not needed...

I will raise a MP for upstream with the chisel slices after retesting and then update this MP so that we use the main chisel-releases branch

**Review by cjdcordeiro — APPROVED** [review]
Thanks. LGTM. I'll review the chisel-releases PRs and I think, given the small slice dependencies, that we can move on with this ;) merging

**Pull request merged**
