### PR TITLE
feat: initialize project for JRE 8

### PR DESCRIPTION
**Pull request by cjdcordeiro**
#### Changes proposed in this pull request:
 - add Dockerfile for building chiselled-jre 8 image
 - add simple hello world test
 - add GH workflow for amd64/arm64 builds and for running the tests

fixes https://github.com/ubuntu-rocks/chiselled-jre/issues/4
fixes https://github.com/ubuntu-rocks/chiselled-jre/issues/5

- [x] I have signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

### CODE REVIEW

**Comment by vpa1977** [comment]
Oh, that was huge effort, nice work  =) 

Some small notes:
- we have forgotten legalise (ASSEMBLY_EXCEPTION and THIRD_PARTY_README)
 - we have left ca-certificates-java hook in the container: `/etc/ca-certificates/update.d/jks-keystore` and import utility in `/usr/share/ca-certificates-java`
 - some broken links: jre/lib/flavormap.properties should be linked to /etc/java-8-openjdk/flavormap.properties
 - same for psfontj2d.properties
 - symlink instead of file lib/amd64/server/libjsig.so (or we could place a file in lib/amd64 so that symlink is not broken)
 - existing hosts, hostname and resolv.conf with 0 length. I wonder if it would be an issue for mapping into container?

**Comment by cjdcordeiro** [comment]
Thanks @vpa1977 

> we have forgotten legalise (ASSEMBLY_EXCEPTION and THIRD_PARTY_README)

Oh right. I've added the ASSEMBLY_EXCEPTION (which I assume is just boilerplate? pls confirm). The THIRD_PARTY_README though, I wasn't sure about it. Is it also a boilerplate with this content: 
https://docs.oracle.com/en/applications/jd-edwards/cross-product/9.2/eotli/java-se-8-third-party-license-readme.html#u10035514 ? @valentincanonical should probably also confirm these 2 files just to be sure.

> we have left ca-certificates-java hook in the container: /etc/ca-certificates/update.d/jks-keystore and import utility in /usr/share/ca-certificates-java

Right. These come from the slice in https://github.com/canonical/chisel-releases/pull/31/files#diff-e415a722593a8a6ded9f6f82e7ac8ffd29a40b9391a4821a51a7b9575f5a8eeaR8. I've removed the two.

> some broken links: jre/lib/flavormap.properties should be linked to /etc/java-8-openjdk/flavormap.properties

should be fixed now.

> same for psfontj2d.properties

should be fixed now.

> symlink instead of file lib/amd64/server/libjsig.so (or we could place a file in lib/amd64 so that symlink is not broken)

should also be fixed now. Plus `/etc/java-8-openjdk/security/blacklisted.certs` that was also missing.

> existing hosts, hostname and resolv.conf with 0 length. I wonder if it would be an issue for mapping into container?

these are set by Docker. You will see them with 0 length if you are exporting the image into a tarball, but that's because 1) we don't include defaults for those files in the chiselled image, and 2) Docker will only populate those when the container starts. You can verify this by running a Java prog that reads and prints `/etc/hostname`, and you'll see it is there and works just fine even when you pass `--hostname <foo>` to `docker run`.

**Review by vpa1977 — APPROVED** [review]

**Comment by valentincanonical** [comment]
Pushed an update to the LICENSE and README files. Updating to use:

- Apache 2.0 for the source code in this project (Dockerfile & others)
- Pointing to the GPLv2 with Classpath exception for the end-user license

**Review by valentincanonical — APPROVED** [review]

**Comment by cjdcordeiro** [comment]
awesome, thanks

**Pull request merged**
